-- 목적: 아산 상세배차 확정 스냅샷과 확정 이후 GLAPS 후처리 변동 이벤트 원장을 관리한다.

CREATE TABLE IF NOT EXISTS public.branch_dispatch_detail_snapshots (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    confirmation_id UUID NOT NULL REFERENCES public.branch_dispatch_confirmations(id) ON DELETE CASCADE,
    branch_id TEXT NOT NULL DEFAULT 'asan',
    dispatch_type TEXT NOT NULL,
    target_date DATE NOT NULL,
    detail_line_key TEXT NOT NULL,
    identity_key TEXT NOT NULL DEFAULT '',
    group_key TEXT NOT NULL DEFAULT '',
    row_fingerprint TEXT NOT NULL DEFAULT '',
    row_values JSONB NOT NULL DEFAULT '{}'::jsonb,
    row_context JSONB NOT NULL DEFAULT '{}'::jsonb,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT branch_dispatch_detail_snapshots_line_key
        UNIQUE (confirmation_id, detail_line_key)
);

CREATE TABLE IF NOT EXISTS public.branch_dispatch_detail_change_events (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    confirmation_id UUID NOT NULL REFERENCES public.branch_dispatch_confirmations(id) ON DELETE CASCADE,
    branch_id TEXT NOT NULL DEFAULT 'asan',
    dispatch_type TEXT NOT NULL,
    target_date DATE NOT NULL,
    event_key TEXT NOT NULL,
    event_order BIGINT GENERATED BY DEFAULT AS IDENTITY,
    change_type TEXT NOT NULL CHECK (change_type IN ('add', 'delete', 'change')),
    event_status TEXT NOT NULL DEFAULT 'pending' CHECK (event_status IN ('pending', 'confirmed')),
    detail_line_key TEXT NOT NULL DEFAULT '',
    identity_key TEXT NOT NULL DEFAULT '',
    group_key TEXT NOT NULL DEFAULT '',
    quantity_delta INTEGER NOT NULL DEFAULT 0,
    before_snapshot JSONB,
    after_snapshot JSONB,
    editable_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    confirmed_by TEXT,
    confirmed_at TIMESTAMPTZ,
    created_by TEXT,
    updated_by TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT branch_dispatch_detail_change_events_key
        UNIQUE (confirmation_id, event_key)
);

CREATE TABLE IF NOT EXISTS public.branch_dispatch_detail_change_history (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    event_id UUID REFERENCES public.branch_dispatch_detail_change_events(id) ON DELETE SET NULL,
    confirmation_id UUID REFERENCES public.branch_dispatch_confirmations(id) ON DELETE SET NULL,
    branch_id TEXT NOT NULL DEFAULT 'asan',
    dispatch_type TEXT NOT NULL,
    target_date DATE NOT NULL,
    action TEXT NOT NULL,
    old_status TEXT,
    new_status TEXT,
    old_payload JSONB,
    new_payload JSONB,
    changed_by TEXT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_branch_dispatch_detail_snapshots_lookup
    ON public.branch_dispatch_detail_snapshots (confirmation_id, active);

CREATE INDEX IF NOT EXISTS idx_branch_dispatch_detail_change_events_lookup
    ON public.branch_dispatch_detail_change_events (branch_id, dispatch_type, target_date, active, event_status, occurred_at, event_order);

CREATE INDEX IF NOT EXISTS idx_branch_dispatch_detail_change_history_lookup
    ON public.branch_dispatch_detail_change_history (branch_id, dispatch_type, target_date, changed_at DESC);

DROP TRIGGER IF EXISTS trg_branch_dispatch_detail_change_events_updated_at ON public.branch_dispatch_detail_change_events;
CREATE TRIGGER trg_branch_dispatch_detail_change_events_updated_at
BEFORE UPDATE ON public.branch_dispatch_detail_change_events
FOR EACH ROW
EXECUTE FUNCTION public.touch_branch_dispatch_confirmation_updated_at();

ALTER TABLE public.branch_dispatch_detail_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branch_dispatch_detail_change_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branch_dispatch_detail_change_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS service_role_branch_dispatch_detail_snapshots ON public.branch_dispatch_detail_snapshots;
DROP POLICY IF EXISTS service_role_branch_dispatch_detail_change_events ON public.branch_dispatch_detail_change_events;
DROP POLICY IF EXISTS service_role_branch_dispatch_detail_change_history ON public.branch_dispatch_detail_change_history;

CREATE POLICY service_role_branch_dispatch_detail_snapshots
ON public.branch_dispatch_detail_snapshots
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

CREATE POLICY service_role_branch_dispatch_detail_change_events
ON public.branch_dispatch_detail_change_events
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

CREATE POLICY service_role_branch_dispatch_detail_change_history
ON public.branch_dispatch_detail_change_history
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

REVOKE ALL ON TABLE public.branch_dispatch_detail_snapshots FROM anon, authenticated;
REVOKE ALL ON TABLE public.branch_dispatch_detail_change_events FROM anon, authenticated;
REVOKE ALL ON TABLE public.branch_dispatch_detail_change_history FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.branch_dispatch_detail_snapshots TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.branch_dispatch_detail_change_events TO service_role;
GRANT SELECT, INSERT ON TABLE public.branch_dispatch_detail_change_history TO service_role;
